server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      enabled: false

  application:
    name: stream-service

  datasource:
    url: jdbc:mysql://localhost:3306/video_stream
    username: devuser
    password: devuser
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 3000
      pool-name: video_stream_pool

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
  data:
    redis:
      host: localhost
      port: 6379
      password: secret
      lettuce:
        pool: # Connection pool settings
          max-active: 10 # Maximum number of active connections in the pool (uses -1 for no limit)
          max-idle: 5 # Maximum number of idle connections in the pool
          min-idle: 5 # Minimum number of idle connections in the pool


